### ISSUE TITLE
Settings. 2012 - Could not save data in elasticsearch due to [cluster_block_exception] index [.wazuh] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)]; (/elastic/api-hostname/1583333020244)

### ISSUE THREAD

**Issue by ossecowner** [wazuh/wazuh-puppet#232] opened 2020-03-18 10:19 UTC
hello dear @manuasir @jm404 
I see this message on kibana:
`Settings. 2012 - Could not save data in elasticsearch due to [cluster_block_exception] index [.wazuh] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)]; (/elastic/api-hostname/1583333020244)`
I did the solution of this link but it Solved only for one day and now this solution doesn't work.
[https://github.com/wazuh/wazuh-kibana-app/issues/1016](url)
I set `"read_only_allow_delete": "false"` but it changes to true Automatically.
```
{
  ".wazuh-version" : {
    "settings" : {
      "index" : {
        "number_of_shards" : "1",
        "blocks" : {
          "read_only_allow_delete" : "true"
        },
        "provided_name" : ".wazuh-version",
        "creation_date" : "1582195362994",
        "number_of_replicas" : "0",
        "uuid" : "K17v4dOdTp6BNkZRuKukMw",
        "version" : {
          "created" : "7030099"
        }
      }
    }
  },
  ".wazuh" : {
    "settings" : {
      "index" : {
        "number_of_shards" : "1",
        "blocks" : {
          "read_only_allow_delete" : "true"
        },
        "provided_name" : ".wazuh",
        "creation_date" : "1583333020273",
        "number_of_replicas" : "1",
        "uuid" : "VjxoSxNES7Sw8ccsoteQrA",
        "version" : {
          "created" : "7030099"
        }
      }
    }
  }
}

```
I have 170 agents and I can't see their events on kibana. please guide me how can I solve this problem.
```
my elasticsearch version is 7.3
kibana 7.3
wazuh 3.9
```
can you help me? I need to fix the problem as soon as possible.
Thank you very much for your response.You have helped me a lot already and I am very grateful.

**Comment by jm404** [comment] 2020-03-18 11:03
Hi @ossecowner, 

The ES cluster usually sets on read-only when reaching the 85% of disk capacity which is what I suspect to be happening.

Please check your ES cluster disk usage with:
```
curl -XGET 'localhost:9200/_cat/allocation?v&pretty'
```

Adding your credentials and address of your cluster.

Best regards,

Jose

**Comment by ossecowner** [comment] 2020-03-18 11:07
shards disk.indices disk.used disk.avail disk.total disk.percent host      ip        node
  1063        172gb     272gb     11.5gb    283.6gb           95 127.0.0.1 127.0.0.1 localhost.localdomain
    16                                                                               UNASSIGNED
So if I increase disk space, the problem will be correct, right?

**Comment by jm404** [comment] 2020-03-18 11:11
Yes, ES will begin to allocate shards as soon as the free space of the disk is 15% or higher. 

Please check https://www.elastic.co/guide/en/elasticsearch/reference/current/disk-allocator.html for detailed info about this process.

Best regards,

Jose

**Comment by ossecowner** [comment] 2020-03-18 11:15
Thank you very much for your uninterrupted response.

**Comment by ossecowner** [comment] 2020-03-18 12:35
@jm404 
I'd rather just delete the logs before five months ago, and I'm looking for a way to do this.

**Comment by ossecowner** [comment] 2020-03-19 10:34
@jm404 
I'd rather delete the data before five months ago from disk, and I'm looking for a way to do this.
size of ossec log files are not more than 32G , disk size is 300G and 95% of it is used,if I want delete older agent's data  (before 4 or 5 months ago) what should I do? where should I delete? Log file size is not large.
![logs](https://user-images.githubusercontent.com/50073170/77058250-6ec6af80-69ea-11ea-8954-c74f87885f1e.png)

**Comment by ossecowner** [comment] 2020-03-23 09:51
Can anyone guide me?
@Zenidd @jm404 @manuasir

**Comment by jm404** [comment] 2020-03-23 10:38
Hi @ossecowner,

You can list your indices by executing: `curl -XGET http://<your_es_address>:9200/_cat/indices`

Output example:

![image](https://user-images.githubusercontent.com/46649922/77306213-a0e05600-6cf7-11ea-839c-1f268330ef1b.png)

The `open` word means they are in use, you can also find the dates and size of such indices.

You can delete any index of your choice by executing: `curl -X DELETE http://<your_es_address>:9200/<your_index_name>?pretty`

After removing the desired indexes you can check your free space and verify that you have enough free space. This process can be automated by using time-based indices which will be automatically removed by [Elasticsearch Curator](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/index.html)

Hope it helps.

Best regards,

Jose

**Comment by ossecowner** [comment] 2020-03-23 12:29
Hi
I did what you said. first I executed `curl -XGET http://<your_es_address>:9200/_cat/indices` and  I saw the result of it and it was ok, after that  I executed the following command and now I see : 


![error](https://user-images.githubusercontent.com/50073170/77316619-60003580-6d27-11ea-8eae-7d801ddab3bd.jpg)


and now I can't execute `curl -XGET http://<your_es_address>:9200/_cat/indices` Again

![error2](https://user-images.githubusercontent.com/50073170/77316630-642c5300-6d27-11ea-929b-f8414b5109f8.jpg)

:(((((((

**Comment by ossecowner** [comment] 2020-03-24 05:52
thanks Jose.
I wish you all the best.

**Comment by jm404** [comment] 2020-03-24 09:20
Glad to help! I'll close this issue as the problem is solved, feel free to open a new one in case you need it.

Let me also mention our Slack channel: https://wazuh.com/community/join-us-on-slack, join our community to share any issue/question and we, aswell as other users, will be glad to help

Best regards

Jose

**Closed by jm404** 2020-03-24 09:20 UTC
Labels: community, question
